### ISSUE TITLE
How to reduce space between two buttons?

### ISSUE THREAD

**Issue by hemangshah** [egmoll7/EMAlertController#4]
Right now, with below code, there are some spaces on action buttons. Is there a way to remove it?

**Sample Code**:

        let alertController = EMAlertController.init(title: "My App", message: "Are you really want to approve?")
        alertController.backgroundViewColor = UIColor.clear
        alertController.backgroundColor = UIColor.white
        alertController.iconImage = #imageLiteral(resourceName: "someImage")
        alertController.cornerRadius = 25.0
        
        let alertActionYes = EMAlertAction.init(title: "Yes", style: .normal) {
            print("Yes")
        }
        let alertActionCancel = EMAlertAction.init(title: "Cancel", style: .cancel) {
            print("Cancel")
        }
        
        alertActionYes.actionBackgroundColor = UIColor.red
        alertActionCancel.actionBackgroundColor = UIColor.red
        alertController.addAction(action: alertActionYes)
        alertController.addAction(action: alertActionCancel)
        self.present(alertController, animated: true, completion: nil)

**Comment by egmoll7** [comment]
A new property will be added in the next commit that will solve this. It will only affect when to buttons are displayed in horizontal. 

```swift
alert.buttonSpacing = 0
// Default spacing = 15
```
