### ISSUE TITLE
Image is not displaying

### ISSUE THREAD

**Issue by hemangshah** [egmoll7/EMAlertController#5]
Image is not displaying.

**Sample Code**:

        let alertController = EMAlertController.init(title: "My App", message: "Are you really want to approve?")
        alertController.backgroundViewColor = UIColor.clear
        alertController.backgroundColor = UIColor.white
        alertController.iconImage = #imageLiteral(resourceName: "someImage")
        alertController.cornerRadius = 25.0
        
        let alertActionYes = EMAlertAction.init(title: "Yes", style: .normal) {
            print("Yes")
        }
        let alertActionCancel = EMAlertAction.init(title: "Cancel", style: .cancel) {
            print("Cancel")
        }
        
        alertActionYes.actionBackgroundColor = UIColor.red
        alertActionCancel.actionBackgroundColor = UIColor.red
        alertController.addAction(action: alertActionYes)
        alertController.addAction(action: alertActionCancel)
        self.present(alertController, animated: true, completion: nil)

**Comment by egmoll7** [comment]
Thanks for reporting, will be fixed on the next commit
